Import required library

In [114]:
import numpy as np
import pandas as pd

Import Datasets

In [115]:
df = pd.read_csv('https://raw.githubusercontent.com/Avik-Jain/100-Days-Of-ML-Code/master/datasets/Data.csv')
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [124]:
X= df.iloc[ : , :3].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [117]:
y= df.iloc[ : , 3].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

Handle NaN

In [125]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp = imp.fit(X[ : , 1:3])
X[ : , 1:3] = imp.transform(X[ : , 1:3])

In [126]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

Encoding Categorical Data

In [128]:
df = df.replace(to_replace = ['Yes','No'],value = ['1','0'])
y= df.iloc[ : , 3].values
y

array(['0', '1', '0', '0', '1', '1', '0', '1', '0', '1'], dtype=object)

In [143]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(X[ : , 0])
le.classes_

array([0, 1, 2], dtype=object)

In [144]:
enc = le.transform(X[ : , 0])
le.inverse_transform(enc)
X[ : , 0]=enc
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, nan],
       [0, 35.0, 58000.0],
       [2, nan, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

Split Data

In [145]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [146]:
X_train

array([[1, 40.0, nan],
       [0, 37.0, 67000.0],
       [2, 27.0, 48000.0],
       [2, nan, 52000.0],
       [0, 48.0, 79000.0],
       [2, 38.0, 61000.0],
       [0, 44.0, 72000.0],
       [0, 35.0, 58000.0]], dtype=object)

In [147]:
y_train

array(['1', '1', '1', '0', '1', '0', '0', '1'], dtype=object)

Feature Scaling

In [148]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_train

array([[ 0.13483997,  0.25315802,         nan],
       [-0.94387981, -0.23014365,  0.44897083],
       [ 1.21355975, -1.84114924, -1.41706417],
       [ 1.21355975,         nan, -1.0242147 ],
       [-0.94387981,  1.54196248,  1.62751925],
       [ 1.21355975, -0.0690431 , -0.14030338],
       [-0.94387981,  0.89756025,  0.94003267],
       [-0.94387981, -0.55234477, -0.43494049]])

In [149]:
X_test = scaler.fit_transform(X_test)
X_test

array([[ 0., -1., -1.],
       [ 0.,  1.,  1.]])